# Generated by Django 5.1.7 on 2025-04-09 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildAugment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('augment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenabuilds.augment')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenabuilds.build')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='augments',
            field=models.ManyToManyField(through='arenabuilds.BuildAugment', to='arenabuilds.augment'),
        ),
        migrations.AddField(
            model_name='build',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenabuilds.champion'),
        ),
        migrations.CreateModel(
            name='BuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenabuilds.build')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arenabuilds.item')),
            ],
        ),
        migrations.AddField(
            model_name='build',
            name='items',
            field=models.ManyToManyField(through='arenabuilds.BuildItem', to='arenabuilds.item'),
        ),
    ]
