# Generated by Django 5.1.7 on 2025-04-09 07:34

import json

import requests
from django.db import migrations


def get_champions():
    url = "https://ddragon.leagueoflegends.com/cdn/15.7.1/data/en_US/champion.json"
    r = requests.get(url)
    data = json.loads(r.text)
    return [
        {
            "name": name,
            "icon_url": f"https://ddragon.leagueoflegends.com/cdn/15.7.1/img/champion/{name}.png",
        }
        for name, _ in data["data"].items()
    ]


def add_champions(apps, schema_editor):
    Champion = apps.get_model("arenabuilds", "Champion")

    for champion in get_champions():
        Champion.objects.create(
            name=champion["name"],
            icon_url=champion["icon_url"],
        )


def remove_champions(apps, schema_editor):
    Champion = apps.get_model("arenabuilds", "Champion")
    Champion.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("arenabuilds", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_champions, remove_champions),
    ]
