# Generated by Django 5.1.7 on 2025-04-09 07:40

from django.db import migrations
import requests
import json


def get_augments():
    url = "https://raw.communitydragon.org/latest/cdragon/arena/en_us.json"

    r = requests.get(url)
    data = json.loads(r.text)
    return [
        {
            "name": augment["name"],
            "icon_url": f"https://raw.communitydragon.org/latest/game/{augment['iconSmall']}",
        }
        for augment in data["augments"]
    ]


def add_augments(apps, schema_editor):
    Augment = apps.get_model("arenabuilds", "Augment")

    for augment in get_augments():
        Augment.objects.create(name=augment["name"], icon_url=augment["icon_url"])


def remove_augments(apps, schema_editor):
    Augment = apps.get_model("arenabuilds", "Augment")
    Augment.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("arenabuilds", "0003_add_items"),
    ]

    operations = [
        migrations.RunPython(add_augments, remove_augments),
    ]
