# Generated by Django 5.1.7 on 2025-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenabuilds', '0004_add_augments'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.GenericIPAddressField()),
                ('success', models.BooleanField()),
            ],
        ),
    ]
